name: forecast_x
description: "Forecast X"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  go_router: ^14.2.7
  flutter_launcher_icons: ^0.13.1
  flutter_platform_widgets: ^6.0.2
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  progress_border: ^0.1.5
  json_annotation: ^4.8.0
  sqflite: ^2.4.1
  path: ^1.9.0
  webview_flutter: ^4.10.0
  webview_flutter_wkwebview: ^3.18.4
  webview_flutter_android: ^4.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/png/app_icon.png" 

flutter:
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/png/
    - assets/images/svg/
    - assets/db_init.sql

  fonts:
    - family: Geologica
      fonts:
        - asset: assets/fonts/geologica/Geologica-Regular.ttf
        - asset: assets/fonts/geologica/Geologica-Bold.ttf
          weight: 700
        - asset: assets/fonts/geologica/Geologica-Medium.ttf
          weight: 500
        - asset: assets/fonts/geologica/Geologica-Light.ttf
          weight: 300
        - asset: assets/fonts/geologica/Geologica-Thin.ttf
          weight: 100
